version: "2"
services:

  web:
    image: florenttorregrosa/docker-drupal-dev:php7
    depends_on:
      - mysql
      - solr
    volumes:
      - .:/project

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql

  solr:
    image: solr:6.1.0-alpine
    volumes:
      - ./conf/solr:/solr-drupal/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - /solr-drupal

  mail:
    image: djfarrelly/maildev
